# Runs at BUILD time (cmake -P): writes ${OUT} with the current `git describe`, but only when it changed, so the PING
# version string always names the firmware actually built and only protocol.c recompiles when it moves.
execute_process(
    COMMAND git describe --always --dirty --abbrev=7
    WORKING_DIRECTORY ${SRC_DIR}
    OUTPUT_VARIABLE desc
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET)
if(NOT desc)
    set(desc "unknown")
endif()

set(content "/* Generated by firmware/cmake/git_desc.cmake at build time. Do not edit. */\n#define FW_GIT_DESC \"${desc}\"\n")
if(EXISTS ${OUT})
    file(READ ${OUT} old)
endif()
if(NOT "${old}" STREQUAL "${content}")
    file(WRITE ${OUT} "${content}")
endif()
